AllCops:
  TargetRubyVersion: 2.4

Layout/EmptyComment:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/WordArray:
  Enabled: false
